# Generated by Django 5.2.1 on 2025-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('authors', models.JSONField()),
                ('date', models.DateField(blank=True, null=True)),
                ('has_woman_author', models.BooleanField(default=False)),
            ],
        ),
    ]
