# Generated by Django 5.2.1 on 2025-05-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paper_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='gender_inference_possible',
            field=models.BooleanField(default=True),
        ),
    ]
