import type { Metadata } from "next";
import "./globals.css";
import { Instrument_Sans } from "next/font/google";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Pick weights you use
  variable: "--font-instrument-sans", // Optional if using CSS vars
});

export const metadata: Metadata = {
  title: "auther.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={instrumentSans.className}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
